### ISSUE TITLE
Make the options page more visually appealing

### ISSUE THREAD

**Issue by Reisclef** [Reisclef/BrowserWordReplace#1]
When I wrote this app, I mainly just wanted it to work when I looked at the news. Given how crazy the news is this year, I thought I'd add an issue for Hacktoberfest to allow somebody to style the options screen nicely. No real preferences other than just keep it simple. No libraries, just basic CSS please!

**Comment by Maxtasy** [comment]
Hi, I would like to do this. Can you assign me?

**Comment by Reisclef** [comment]
@Maxtasy , that's done! However, I just was reading through the hacktoberfest information, and I'm not actually sure that this repository can count towards the PRs for hacktoberfest. I think it does, but there's conflicting information.

The profile page says: "Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate." but the FAQ states: "any pull request made on a public repository counts, whether it’s attached to a hacktoberfest issue or not."

I think I've added that topic correctly, but this is the first time I've done this! I'll remove the label, just to avoid confusion. Just wanted to let you know in case that was your intention. Sorry if there's any problem, and thanks for your interest! Hopefully I've done everything right and it will count! :)

**Comment by Maxtasy** [comment]
Yeah no problem :D

**Comment by Reisclef** [comment]
Thanks! Looks great! That's been merged! Hope it counts towards your Hacktoberfest, if you're taking part! :)
